### ISSUE TITLE
Inquiry Regarding UITabBarController Handling in SwiftUICoordinator

### ISSUE THREAD

**Issue by hihelloluigi** [erikdrobne/SwiftUICoordinator#33]
Hello Erik,

First of all, I would like to extend my sincere compliments on the development of the SwiftUICoordinator library. 
It's impressively structured and serves as a great resource for the SwiftUI community. 
Your effort in making this library accessible and efficient is genuinely appreciated.

I'm currently exploring SwiftUICoordinator for a project and I am particularly interested in understanding how it could be integrated with UITabBarController. 
Given the distinct architecture of SwiftUI, I'm curious about the best practices you would recommend for implementing a UITabBarController in conjunction with your coordinator pattern.

Could you provide some insights or examples on how to effectively manage UITabBarController using SwiftUICoordinator? Any guidance or recommendations you could offer would be incredibly helpful, as I aim to leverage the full potential of your library in a way that aligns with SwiftUI's paradigms.

Thank you in advance for your time and assistance. I look forward to any suggestions or advice you might have.

Best regards,

Luigi Aiello

**Comment by erikdrobne** [comment]
Hey @hihelloluigi!

Thank you for your kind words and I appreciate that you like the SDK. 🙏
I plan to keep it active and add new features on the go but will need some extra details about your situation.

Are you using `TabView` or `UITabBarController`?
Can you provide me with some code examples, please?

Best,

Erik

**Comment by hihelloluigi** [comment]
Hi Erik,

I'm relatively new to the coordinator pattern and would appreciate your insights on whether my approach makes sense. Here's how I'm structuring my app with SwiftUICoordinator:

1. I've designated an "AppCoordinator" as the entry point for my app.

2. Depending on whether a token exists in the keychain, my app should either show a login form or a tab-based interface.

3. If no token is present, I plan to use a "RegistrationCoordinator," implemented as a NavigationView using your library that I append to AppCoordinator.

4. After a successful registration or login within the RegistrationCoordinator, I'd like to transition to a "TabBarCoordinator", but before adding my new coordinator I have to remove the "RegistrationCoordinator", to make my "TabBarCoordinator" just above the AppCoordinator. This should be a UITabBarController, with each tab containing its own Coordinator and Navigation.

5. In case of a user logout, I need to switch back from the TabBarCoordinator to the RegistrationCoordinator.

Could you provide guidance or examples on how to set up these coordinators and transitions effectively within SwiftUICoordinator? Your help would be greatly appreciated.

Thanks again for your support and your excellent library!

Best regards,
Luigi Aiello

**Comment by jedmund** [comment]
Hi! Can you speak a little bit more on how to use this library with a TabBarController?

I'm trying to implement something similar to @hihelloluigi and I'm currently stuck trying to figure out how to show the tab bar above the coordinator views. If I render the tab bar inside of the coordinator, it gets covered when new views are pushed onto the stack.

My next thought is to set my TabBarCoordinator's navigationController to a UITabBarController but that would require that I fork the library and do a ton of changes—I feel like there has to be a better solution.

Preferably, I'd like to be able to make a purely SwiftUI tab bar (I'm making something custom), but if UITabBarController is going to make my life significantly easier, I can make that work. I just can't figure out where to actually render/set up the tab bar such that it shows up in the correct place.

Thanks!

**Comment by erikdrobne** [comment]
Hi @jedmund. I see what you're trying to achieve here, but I haven't been (yet) actively working on the `UITabBarController` integration with the `SwiftUICoordinator` library.

Before I start working on the solution I have some questions:
- The main goal is to show the tab bar above some coordinator with the views?
- Can you share some codebase that will help us to understand and elaborate on this challenge?

If you already have a solution feel free to open a PR.
